var menu = {
    "Birria":[
        {name: "Birria de Chivo",price: "$16.99", desc: "Con Tortillas" },
        {name: "Birria de Res",price: "$15.99", desc: "Con Tortillas" },
        {name: "Quesa-birrias", price: "$5.99", desc: "Servida con Arroz y caldo." },
    ],
    "Desayunos": [
        { name: "Omelet", price: "$12.50", desc: "", img:"desayunos"},
        { name: "Pancakes", price: "$10.75", desc: "" },
        { name: "Huevos Rancheros", price: "$10.75", desc: ""},
        { name: "Huevos a la Mexicana", price: "$10.75", desc: "" },
        { name: "Huevos con Chorizo", price: "$10.75",  desc: ""},
        { name: "Chilaquiles Verdes o Rojos", price: "$16.50", desc: "Bistec, Chorizo o Bacon" },
    ],
    "Tacos":[
        { name: "Tacos de Birria", price: "$2.50", desc: "Cebolla, cilantro, guacamole, salsas" },
        { name: "Tacos de Asada", price: "$2.50", desc: "Cebolla, cilantro, guacamole, salsas" },
        { name: "Tacos de Pastor", price: "$2.50", desc: "Cebolla, cilantro, guacamole, salsas" },
        { name: "Tacos de Pollo", price: "$2.50", desc: "Cebolla, cilantro, guacamole, salsas" },
        { name: "Tacos de Carnitas", price: "$2.50", desc: "Cebolla, cilantro, guacamole, salsas" },
        { name: "Tacos de Camaron", price: "$3.50", desc: "Cebolla, cilantro, guacamole, salsas" },
        { name: "Tacos de Pescado", price: "$3.00", desc: "Cebolla, cilantro, guacamole, salsas" },

        { name: "Charola de Tacos de Birria", price: "$40.00", desc: "Cebolla, cilantro, guacamole, salsas" },
        { name: "Charola de Tacos de Asada", price: "$40.00", desc: "Cebolla, cilantro, guacamole, salsas" },
        { name: "Charola de Tacos de Pastor", price: "$40.00", desc: "Cebolla, cilantro, guacamole, salsas" },
        { name: "Charola de Tacos de Pollo", price: "$40.00", desc: "Cebolla, cilantro, guacamole, salsas" },
        { name: "Charola de Tacos de Carnitas", price: "$40.00", desc: "Cebolla, cilantro, guacamole, salsas" },
        { name: "Charola de Tacos de Camaron", price: "$48.00", desc: "Cebolla, cilantro, guacamole, salsas" },
        { name: "Charola de Tacos de Pescado", price: "$48.00", desc: "Cebolla, cilantro, guacamole, salsas" },
    ],
    "Burritos":[
        { name: "Burrito mojado", price: "$11.99", desc: "Servido beans, arroz, cilantro, cebolla, salsa roja o verde"},
        { name: "Birria", price: "$8.50", desc: ""},
        { name: "Asada", price: "$8.50", desc: ""},
        { name: "Pastor", price: "$8.50", desc: ""},
        { name: "Pollo", price: "$8.50", desc: ""},
        { name: "Carnitas", price: "$8.50", desc: ""},
        { name: "Camaron", price: "$11.50", desc: ""},
    ],
    "Tortas":[
        { name: "Birria", price: "$8.25", desc: "Avocado, Lechuga, Tomato, Mayonesa, Frijoles"},
        { name: "Asada", price: "$8.25", desc: "Avocado, Lechuga, Tomato, Mayonesa, Frijoles"},
        { name: "Pastor", price: "$8.25", desc: "Avocado, Lechuga, Tomato, Mayonesa, Frijoles"},
        { name: "Pollo", price: "$8.25", desc: "Avocado, Lechuga, Tomato, Mayonesa, Frijoles"},
        { name: "Carnitas", price: "$8.25", desc: "Avocado, Lechuga, Tomato, Mayonesa, Frijoles"},
    ],
    "Hamburguesas":[
        { name: "Hamburguesa de res", price: "$10.75", desc: ""},
        { name: "Hamburguesa de pollo", price: "$9.75", desc: ""},
        { name: "Bacon Burguer", price: "$10.75", desc: ""},
        { name: "BBQ Burguer", price: "$10.75", desc: ""}
    ],
    "Sides":[
        {name: "Tortilla", price: "$1.25", desc: ""},
        {name: "Crema", price: "$1.50", desc: ""},
        {name: "Queso", price: "$2.50", desc: "" },
        {name: "Arroz con frijoles", price: "$3.00", desc: ""},
        {name: "Chips en salsa", price: "$3.00", desc: ""},
        {name: "Chiles toreados", price: "$2.00", desc: ""},
    ],
    "Mariscos":[],
    "Platillos":[],
    "Caldos":[
        {name: "Menudo",price: "$11.95", desc: ""},
        {name: "Albondiga Caldo de Res",price: "$12.50",  desc: ""},
        {name: "Caldo de Pollo",price: "$12.50", desc: ""},
        {name: "Pozole",price: "$12.50", desc: "" }
    ],
    "Ensaladas":[
        {name: "Ensalada de camarón", price: "$13.99", desc: "" },
        {name: "Chicken Cesar Salad", price: "$12.99", desc: "" },
        {name: "Garden Salad", price: "$7.99", desc: "" },
        {name: "Ensalada con pollo", price: "$8.99", desc: "" }
    ],
    "Nachos":[],
    "Alitas":[],
    "Para Niños":[
        { name: "Taquitos dorados", price: "$5.00", desc: "Servido con Arroz y Frijoles"},
        { name: "Flautas de pollo", price: "$5.50", desc: "Servido con Arroz y Frijoles"},
        { name: "Enchilada", price: "$4.50", desc: "Servido con Arroz y Frijoles"},
        { name: "Quesadilla", price: "$3.50", desc: "Servido con Arroz y Frijoles"},
        { name: "Papas fritas", price: "$4.00", desc: "Servido con Arroz y Frijoles"},
        { name: "Chicken tender", price: "$5.00", desc: "Servido con Arroz y Frijoles"},
        { name: "Hamburguesa con papas", price: "$8.25", desc: "Servido con Arroz y Frijoles"},       
    ],
    "Soda":[],
    "Bebidas Alc.":[],
    "Postres":[]
}