var menu = {
    "Birria":[
        {name: "Birria de Chivo",price: "$16.99", desc: "Con Tortillas" },
        {name: "Birria de Res",price: "$15.99", desc: "Con Tortillas" },
        {name: "Quesa-birrias", price: "$5.99", desc: "Servida con Arroz y caldo." },
    ],
    "Desayunos": [
        {name: "Omelet", price: "$12.50", desc: "", },
        {name: "Pancakes", price: "$10.75", desc: "" },
        {name: "Huevos Rancheros", price: "$10.75", desc: ""},
        {name: "Huevos a la Mexicana", price: "$10.75", desc: "" },
        {name: "Huevos con Chorizo", price: "$10.75",  desc: ""},
        {name: "Chilaquiles Verdes o Rojos", price: "$16.50", desc: "Bistec, Chorizo o Bacon" },
    ],
    "Tacos":[
        {name: "Tacos de Birria", price: "$2.50", desc: "Cebolla, cilantro, guacamole, salsas" },
        {name: "Tacos de Asada", price: "$2.50", desc: "Cebolla, cilantro, guacamole, salsas" },
        {name: "Tacos de Pastor", price: "$2.50", desc: "Cebolla, cilantro, guacamole, salsas" },
        {name: "Tacos de Pollo", price: "$2.50", desc: "Cebolla, cilantro, guacamole, salsas" },
        {name: "Tacos de Carnitas", price: "$2.50", desc: "Cebolla, cilantro, guacamole, salsas" },
        {name: "Tacos de Camaron", price: "$3.50", desc: "Cebolla, cilantro, guacamole, salsas" },
        {name: "Tacos de Pescado", price: "$3.00", desc: "Cebolla, cilantro, guacamole, salsas" },

        {name: "Charola (Birria)", price: "$40.00", desc: "Cebolla, cilantro, guacamole, salsas" },
        {name: "Charola (Asada)", price: "$40.00", desc: "Cebolla, cilantro, guacamole, salsas" },
        {name: "Charola (Pastor)", price: "$40.00", desc: "Cebolla, cilantro, guacamole, salsas" },
        {name: "Charola (Pollo)", price: "$40.00", desc: "Cebolla, cilantro, guacamole, salsas" },
        {name: "Charola (Carnitas)", price: "$40.00", desc: "Cebolla, cilantro, guacamole, salsas" },
        {name: "Charola (Camaron)", price: "$48.00", desc: "Cebolla, cilantro, guacamole, salsas" },
        {name: "Charola (Pescado)", price: "$48.00", desc: "Cebolla, cilantro, guacamole, salsas" },
    ],
    "Burritos":[
        {name: "Burrito mojado", price: "$11.99", desc: "Servido beans, arroz, cilantro, cebolla, salsa roja o verde"},
        {name: "Birria", price: "$8.50", desc: ""},
        {name: "Asada", price: "$8.50", desc: ""},
        {name: "Pastor", price: "$8.50", desc: ""},
        {name: "Pollo", price: "$8.50", desc: ""},
        {name: "Carnitas", price: "$8.50", desc: ""},
        {name: "Camaron", price: "$11.50", desc: ""},
    ],
    "Tortas":[
        {name: "Birria", price: "$8.25", desc: "Avocado, Lechuga, Tomato, Mayonesa, Frijoles"},
        {name: "Asada", price: "$8.25", desc: "Avocado, Lechuga, Tomato, Mayonesa, Frijoles"},
        {name: "Pastor", price: "$8.25", desc: "Avocado, Lechuga, Tomato, Mayonesa, Frijoles"},
        {name: "Pollo", price: "$8.25", desc: "Avocado, Lechuga, Tomato, Mayonesa, Frijoles"},
        {name: "Carnitas", price: "$8.25", desc: "Avocado, Lechuga, Tomato, Mayonesa, Frijoles"},
    ],
    "Hamburguesas":[
        {name: "Hamburguesa de res", price: "$10.75", desc: ""},
        {name: "Hamburguesa de pollo", price: "$9.75", desc: ""},
        {name: "Bacon Burguer", price: "$10.75", desc: ""},
        {name: "BBQ Burguer", price: "$10.75", desc: ""}
    ],
    "Sides":[
        {name: "Tortilla", price: "$1.25", desc: ""},
        {name: "Crema", price: "$1.50", desc: ""},
        {name: "Queso", price: "$2.50", desc: "" },
        {name: "Arroz con frijoles", price: "$3.00", desc: ""},
        {name: "Chips en salsa", price: "$3.00", desc: ""},
        {name: "Chiles toreados", price: "$2.00", desc: ""},
    ],
    "Mariscos":[
        {name: "Cocktel de Camaron", price: "$00.00", desc: ""},
        {name: "Cocktel de Pulpo", price: "$00.00", desc: ""},
        {name: "Cocktel Mixto", price: "$00.00", desc: ""},
        {name: "Tostada de Camaron", price: "$00.00", desc: "Crudo o cocido"},
        {name: "Tostada Mixto", price: "$00.00", desc: ""},
        {name: "Molcajete de Mariscos", price: "$00.00", desc: "Camaron, Pulpo, Ostion"},
        {name: "Torre de Mariscos", price: "$00.00", desc: "Camaron cocido, Camaron crudo, Pulpo"},
        {name: "Ostiones", price: "$00.00", desc: ""},
        {name: "Ostiones Supremo", price: "$00.00", desc: "Servido con 2 shots de tequila"},
        {name: "Charola de Camarones Cerveza", price: "$00.00", desc: "4 o 6 Cerveza"},
        {name: "Camaron Botana", price: "$00.00", desc: ""},
        {name: "Fried Camaron", price: "$00.00", desc: ""},
        {name: "Molcajete de Mariscos", price: "$00.00", desc: "Con 4 cervezas"},
    ],
    "Platillos":[
        {name: "Costilla de puerco en salsa roja o verde",price: "$13.99", desc:"Arroz, frijoles, tortillas"},
        {name: "Chile Verde",price: "$13.99", desc:"Arroz, frijoles, tortillas"},
        {name: "Chile Relleno",price: "$14.99", desc:"Arroz, frijoles, tortillas"},
        {name: "Carnitas Plate",price: "$13.99", desc:"Arroz, frijoles, tortillas"},
        {name: "Fajitas de Pollo",price: "$13.99", desc:"Arroz, frijoles, tortillas"},
        {name: "Fajitas de Res",price: "$15.99", desc:"Arroz, frijoles, tortillas"},
        {name: "Fajitas Combo",price: "$22.99", desc:"(Pollo, Bistec, Camaron) Arroz, frijoles, tortillas"},
        {name: "Enchilada de Queso",price: "$11.99", desc:"Arroz, frijoles, tortillas"},
        {name: "Enchilada Ranchera",price: "$12.99", desc:"Arroz, frijoles, tortillas"},
        {name: "Enchilada de Camaron",price: "$13.99", desc:"Arroz, frijoles, tortillas"},
        {name: "Came Asada",price: "$15.99", desc:"Arroz, frijoles, tortillas"},
        {name: "Mar y Tierra",price: "$22.99", desc:"Arroz, frijoles, tortillas"},
        {name: "Flautas Dinner",price: "$14.99", desc:"Arroz, frijoles, tortillas"},
        {name: "Bisteck a la Mexicana",price: "$16.99", desc:"Arroz, frijoles, tortillas"},
        {name: "Tampiqueña",price: "$16.99", desc:"Arroz, frijoles, tortillas"},
        {name: "Camarones al Mojo de Ajo",price: "$18.99", desc:"Arroz, frijoles, tortillas"},
    ],
    "Caldos":[
        {name: "Menudo",price: "$11.95", desc: ""},
        {name: "Albondiga Caldo de Res",price: "$12.50",  desc: ""},
        {name: "Caldo de Pollo",price: "$12.50", desc: ""},
        {name: "Pozole",price: "$12.50", desc: "" }
    ],
    "Ensaladas":[
        {name: "Ensalada de camarón", price: "$13.99", desc: "" },
        {name: "Chicken Cesar Salad", price: "$12.99", desc: "" },
        {name: "Garden Salad", price: "$7.99", desc: "" },
        {name: "Ensalada con pollo", price: "$8.99", desc: "" }
    ],
    "Para Niños":[
        {name: "Taquitos dorados", price: "$5.00", desc: "Servido con Arroz y Frijoles"},
        {name: "Flautas de pollo", price: "$5.50", desc: "Servido con Arroz y Frijoles"},
        {name: "Enchilada", price: "$4.50", desc: "Servido con Arroz y Frijoles"},
        {name: "Quesadilla", price: "$3.50", desc: "Servido con Arroz y Frijoles"},
        {name: "Papas fritas", price: "$4.00", desc: "Servido con Arroz y Frijoles"},
        {name: "Chicken tender", price: "$5.00", desc: "Servido con Arroz y Frijoles"},
        {name: "Hamburguesa con papas", price: "$8.25", desc: ""},       
    ],
    "Postres":[
        {name: "Flan", price: "$00.00", desc: ""},
        {name: "Churros", price: "$00.00", desc: ""},       
        {name: "Nieve de Cereal", price: "$00.00", desc: ""},       
    ],
    "Botanas / Appetizers":[
        {name: "Quesadilla de Asada", price: "$10.50", desc: "" },
        {name: "Quesadilla de Queso", price: "$8.75", desc: "" },
        {name: "Quesadilla de Pollo", price: "$9.75", desc: "" },
        {name: "Quesadilla de Camaron", price: "$11.99", desc: "" },
        {name: "Quesadilla de Carnitas", price: "$9.75", desc: "" },
        {name: "Nachos de Asada", price: "$0.00", desc: "" },
        {name: "Nachos de Pollo", price: "$0.00", desc: "" },
        {name: "Nachos de Carnitas", price: "$0.00", desc: "" },
        {name: "Guacamole / appetizers", price: "$8.25", desc: "" },
        {name: "Alitas BBQ", price: "$0.00", desc: "" },
        {name: "Alitas Buffalo", price: "$0.00", desc: "" },
        {name: "Papa Frita", price: "$6.25", desc: "" },
        {name: "Papa Frita con Queso", price: "$7.25", desc: "" },
        {name: "Papa Frita con Asada", price: "$10.50", desc: "" },
        {name: "Sweet potatoes", price: "$8.25", desc: "" },
        {name: "Flautas", price: "$9.50", desc: "4pz, Pollo/Carnitas, con lechuga, tomate, guacamole, sour cream" },
        {name: "Taquitos dorados", price: "$8.75", desc: "" },
        {name: "Molcajete Mix", price: "$19.75", desc: "Carne, pollo, nopales, queso fresco, salsa picante, tortillas" },
    ],
    "Bebidas alcoholicas":[
        {name: "Modelo", price: "$5.00", desc: "" },
        {name: "Corona", price: "$5.00", desc: "" },
        {name: "Pacifico", price: "$5.00", desc: "" },
        {name: "XX Equis", price: "$5.00", desc: "" },
        {name: "Negra Modelo", price: "$5.00", desc: "" },
        {name: "Bud Light", price: "$4.00", desc: "" },
        {name: "Corona Light", price: "$4.00", desc: "" },
        {name: "Ultra Light", price: "$4.00", desc: "" },
        {name: "Cubeta de cerveza", price: "$0.00", desc: "" },
        {name: "Margarita", price: "$0.00", desc: "" },
        {name: "Margarita premium", price: "$0.00", desc: "" },
        {name: "Margarita de fresa", price: "$0.00", desc: "" },
        {name: "Margarita de mango", price: "$0.00", desc: "" },
        {name: "Margarita premium", price: "$0.00", desc: "" },
        {name: "Piña colada", price: "$0.00", desc: "Fresa o mango" },
        {name: "Mangoneadas", price: "$0.00", desc: "" },
        {name: "Paloma", price: "$0.00", desc: "" },
        {name: "Tequila Patron Silver", price: "$0.00", desc: "" },
        {name: "Tequila Don Julio 70", price: "$0.00", desc: "" },
        {name: "Tequila Cazadores", price: "$0.00", desc: "" },
        {name: "Tequila Corralejo", price: "$0.00", desc: "" },
        {name: "Tequila Centenario", price: "$0.00", desc: "" },
        {name: "Tequila Herradura", price: "$0.00", desc: "" },
        {name: "Tequila 1800", price: "$0.00", desc: "" },
    ],
}